### ISSUE TITLE
What is the version of opnecv when the author compiles it? I am using 3.2.0 to compile and get an error

### ISSUE THREAD

**Issue by CHANdaFeng** [FletcherFT/oculus_sonar_driver#1]
What is the version of opnecv when the author compiles it? I am using 3.2.0 to compile and get an error

[ 79%] Built target oculus_sonar_driver_generate_messages
In file included from /usr/include/opencv2/core.hpp:54:0,
                 from /usr/include/opencv2/core/core.hpp:48,
                 from /home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/DrawSonar.h:13,
                 from /home/xiaofeng/catkin_ws/src/sonar_image_proc/lib/SonarDrawer.cpp:4:
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h: In function ‘void sonar_image_proc::overlayImage(const cv::Mat&, const cv::Mat&, cv::Mat&)’:
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:23:30: error: ‘cv::traits’ has not been declared
   CV_Assert(bg.type() == cv::traits::Type<VB>::value &&
                              ^
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:23:45: error: expected primary-expression before ‘>’ token
   CV_Assert(bg.type() == cv::traits::Type<VB>::value &&
                                             ^
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:23:48: error: ‘::value’ has not been declared
   CV_Assert(bg.type() == cv::traits::Type<VB>::value &&
                                                ^
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:23:48: note: suggested alternative: ‘valloc’
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:24:30: error: ‘cv::traits’ has not been declared
             fg.type() == cv::traits::Type<VF>::value && bg.size() == fg.size());
                              ^
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:24:45: error: expected primary-expression before ‘>’ token
             fg.type() == cv::traits::Type<VF>::value && bg.size() == fg.size());
                                             ^
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:24:48: error: ‘::value’ has not been declared
             fg.type() == cv::traits::Type<VF>::value && bg.size() == fg.size());
                                                ^
/home/xiaofeng/catkin_ws/src/sonar_image_proc/include/sonar_image_proc/OverlayImage.h:24:48: note: suggested alternative: ‘valloc’
sonar_image_proc/CMakeFiles/sonar_image_proc.dir/build.make:110: recipe for target 'sonar_image_proc/CMakeFiles/sonar_image_proc.dir/lib/SonarDrawer.cpp.o' failed
make[2]: *** [sonar_image_proc/CMakeFiles/sonar_image_proc.dir/lib/SonarDrawer.cpp.o] Error 1
CMakeFiles/Makefile2:3290: recipe for target 'sonar_image_proc/CMakeFiles/sonar_image_proc.dir/all' failed
make[1]: *** [sonar_image_proc/CMakeFiles/sonar_image_proc.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Invoking "make -j20 -l20" failed

**Comment by CHANdaFeng** [comment]
3.4.15

**Comment by FletcherFT** [comment]
Try opencv 4.5. That is what I used for the build.

**Comment by CHANdaFeng** [comment]
Thanks to the author, I used cv3.4.15 for the build successfully
