### ISSUE TITLE
about ip address and port

### ISSUE THREAD

**Issue by silenceghost** [FletcherFT/oculus_sonar_driver#2]
my sonar's ip address and port are not default ，which file can I change the ip address and port for my sonar, thank you for your anwser

**Comment by FletcherFT** [comment]
IP address is configurable and exposed as the [ip_address argument](https://github.com/FletcherFT/oculus_sonar_driver/blob/f591f49bfb8f6457db14115d28450fc1b68a5cc6/launch/default_ros.launch#L20) and [parameter](https://github.com/FletcherFT/oculus_sonar_driver/blob/f591f49bfb8f6457db14115d28450fc1b68a5cc6/launch/default_ros.launch#L36). 

The port on the other hand is hardcoded in the [liboculus library](https://github.com/apl-ocean-engineering/liboculus/blob/7f2f82b9b58c6f10e76f820f8313b4f387597e9d/include/liboculus/Constants.h#L44), Try changing that to your configured port (or better, just configure your oculus' port to 52100 and see if you get connection).

**Comment by silenceghost** [comment]
thank you for ur anwser ,I will try it by the way that u said,thank you again
